# Site settings
title: "Omar's HotSpot"
email: elmimouni.o.i@gmail.com
description: "Omar's personal blog"
baseurl: ""
url: "https://elmimouni.net"
title_description: "Hi there, and welcome to my personal blog."
title_image: ""
google_analytics: true
disqus_account: elmiomar
github_repository: https://github.com/elmiomar
addthis_id: ""
post_limit: 5

# Social usernames/URLs
twitter_username: _omarilias_
github_username: elmiomar
linkedin_link: https://linkedin.com/in/elmimouni
facebook_link: https://www.facebook.com/oielmimouni

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

# host: "192.168.1.173"

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
